CRITICAL - 2024-04-03 19:08:35 --> CodeIgniter\Exceptions\FrameworkException: The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 252.
 1 SYSTEMPATH\CodeIgniter.php(252): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(214): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
ERROR - 2024-04-03 17:42:28 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Home.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Home->index()
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Home.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Home->index()
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:42:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Home.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 17:48:26 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:48:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Eczane.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 17:49:18 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:49:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Eczane.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 17:49:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:49:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Eczane.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 17:49:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:49:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Eczane.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 17:49:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:49:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Eczane.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 17:49:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:49:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Eczane.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 17:50:01 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:50:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Eczane.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 17:50:01 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:50:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Eczane.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 17:50:01 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:50:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Eczane.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 17:50:02 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:50:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Eczane.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 17:50:53 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:50:53 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Eczane.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 17:51:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:51:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Eczane.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 17:51:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index('')
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index('')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:51:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Eczane.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index('')
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 17:53:03 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Home.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Home->index()
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Home.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Home->index()
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:53:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Home.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 17:53:08 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#7 C:\xampp\htdocs\VTYS\app\Controllers\Home.php(9): view('welcome_message')
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Home->index()
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\app\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#3 C:\xampp\htdocs\VTYS\system\View\View.php(228): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\VTYS\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\VTYS\system\Common.php(1178): CodeIgniter\View\View->render('welcome_message', Array, true)
#6 C:\xampp\htdocs\VTYS\app\Controllers\Home.php(9): view('welcome_message')
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Home->index()
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2024-04-03 17:53:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\welcome_message.php(4): CodeIgniter\Database\BaseConnection->query('SELECT * FROM vtys')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\welcome_message.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 6 APPPATH\Controllers\Home.php(9): view('welcome_message')
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 18:00:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(11): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(11): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#5 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 18:00:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vtys`', [], false)
 3 APPPATH\Models\EczaneModel.php(11): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 18:00:45 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(11): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(11): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#5 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 18:00:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vtys`', [], false)
 3 APPPATH\Models\EczaneModel.php(11): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:01:13 --> TypeError: App\Controllers\Eczane::index(): Return value must be of type string, none returned
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:01:14 --> TypeError: App\Controllers\Eczane::index(): Return value must be of type string, none returned
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:01:18 --> TypeError: App\Controllers\Eczane::index(): Return value must be of type string, none returned
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:01:19 --> TypeError: App\Controllers\Eczane::index(): Return value must be of type string, none returned
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:01:19 --> TypeError: App\Controllers\Eczane::index(): Return value must be of type string, none returned
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:01:19 --> TypeError: App\Controllers\Eczane::index(): Return value must be of type string, none returned
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:01:19 --> TypeError: App\Controllers\Eczane::index(): Return value must be of type string, none returned
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:01:24 --> TypeError: App\Controllers\Eczane::index(): Return value must be of type string, none returned
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:01:28 --> TypeError: App\Controllers\Eczane::index(): Return value must be of type string, none returned
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:01:28 --> TypeError: App\Controllers\Eczane::index(): Return value must be of type string, none returned
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:01:28 --> TypeError: App\Controllers\Eczane::index(): Return value must be of type string, none returned
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:01:29 --> TypeError: App\Controllers\Eczane::index(): Return value must be of type string, none returned
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:01:29 --> TypeError: App\Controllers\Eczane::index(): Return value must be of type string, none returned
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:01:30 --> TypeError: App\Controllers\Eczane::index(): Return value must be of type string, none returned
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:01:30 --> TypeError: App\Controllers\Eczane::index(): Return value must be of type string, none returned
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:02:12 --> Error: Class "App\Controllers\EczaneModel" not found
in APPPATH\Controllers\Eczane.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 18:02:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(11): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(11): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#5 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 18:02:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vtys`', [], false)
 3 APPPATH\Models\EczaneModel.php(11): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 18:02:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(11): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(11): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#5 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 18:02:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vtys`', [], false)
 3 APPPATH\Models\EczaneModel.php(11): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:03:52 --> Error: Object of class CodeIgniter\Database\MySQLi\Connection could not be converted to string
in APPPATH\Controllers\Eczane.php on line 13.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:03:52 --> Error: Object of class CodeIgniter\Database\MySQLi\Connection could not be converted to string
in APPPATH\Controllers\Eczane.php on line 13.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 18:06:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#5 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 18:06:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vtys`', [], false)
 3 APPPATH\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 18:11:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#5 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 18:11:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vtys`', [], false)
 3 APPPATH\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 18:11:50 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#5 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 18:11:50 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vtys`', [], false)
 3 APPPATH\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 18:15:17 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#5 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 18:15:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vtys`', [], false)
 3 APPPATH\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 18:15:18 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#5 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 18:15:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vtys`', [], false)
 3 APPPATH\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 18:15:19 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#5 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 18:15:19 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vtys`', [], false)
 3 APPPATH\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 18:15:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#5 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 18:15:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vtys`', [], false)
 3 APPPATH\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 18:15:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#5 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 18:15:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vtys`', [], false)
 3 APPPATH\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 18:16:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'test', 3306, '', 0)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#8 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\VTYS\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\VTYS\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\VTYS\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\VTYS\app\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\VTYS\app\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
#5 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(943): App\Controllers\Eczane->index()
#6 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
#7 C:\xampp\htdocs\VTYS\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\VTYS\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 18:16:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `vtys`', [], false)
 3 APPPATH\Models\EczaneModel.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Eczane.php(12): App\Models\EczaneModel->test()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:24:34 --> ErrorException: Attempt to read property "id" on array
in APPPATH\Controllers\Eczane.php on line 12.
 1 APPPATH\Controllers\Eczane.php(12): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "id" on array', 'C:\\xampp\\htdocs\\VTYS\\app\\Controllers\\Eczane.php', 12)
 2 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 3 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:26:25 --> ErrorException: Undefined variable $data
in APPPATH\Views\login.php on line 3.
 1 APPPATH\Views\login.php(3): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'C:\\xampp\\htdocs\\VTYS\\app\\Views\\login.php', 3)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\login.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('login', [], true)
 5 APPPATH\Controllers\Eczane.php(12): view('login', [...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:26:48 --> ErrorException: Undefined variable $data
in APPPATH\Views\login.php on line 3.
 1 APPPATH\Views\login.php(3): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'C:\\xampp\\htdocs\\VTYS\\app\\Views\\login.php', 3)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\login.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('login', [], true)
 5 APPPATH\Controllers\Eczane.php(13): view('login', [...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:26:48 --> ErrorException: Undefined variable $data
in APPPATH\Views\login.php on line 3.
 1 APPPATH\Views\login.php(3): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'C:\\xampp\\htdocs\\VTYS\\app\\Views\\login.php', 3)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\login.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('login', [], true)
 5 APPPATH\Controllers\Eczane.php(13): view('login', [...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 18:26:49 --> ErrorException: Undefined variable $data
in APPPATH\Views\login.php on line 3.
 1 APPPATH\Views\login.php(3): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'C:\\xampp\\htdocs\\VTYS\\app\\Views\\login.php', 3)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\VTYS\\app\\Views\\login.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('login', [], true)
 5 APPPATH\Controllers\Eczane.php(13): view('login', [...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Eczane->index()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Eczane))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
